# Generated by Django 5.0.6 on 2026-05-28 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(choices=[('bag', 'Shopping bag'), ('utensils', 'Utensils'), ('car', 'Car'), ('home', 'Home'), ('cart', 'Cart'), ('cash', 'Cash'), ('coffee', 'Coffee'), ('star', 'Star')], default='bag', max_length=20)),
                ('color', models.CharField(choices=[('beige', 'Beige'), ('green', 'Green'), ('peach', 'Peach'), ('cream', 'Cream'), ('mint', 'Mint'), ('sage', 'Sage')], default='beige', max_length=20)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('source', models.CharField(blank=True, help_text='Person/company who sent money (for income)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
    ]
