# Generated by Django 5.0.6 on 2026-05-28 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_friend_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendledger',
            name='unique_friend_ledger',
        ),
        migrations.RemoveConstraint(
            model_name='friendsavings',
            name='unique_friend_savings',
        ),
        migrations.AlterUniqueTogether(
            name='friendledger',
            unique_together={('user', 'friend_name')},
        ),
        migrations.AlterUniqueTogether(
            name='friendsavings',
            unique_together={('user', 'friend_name')},
        ),
    ]
