# Generated by Django 5.0.6 on 2026-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_friendledger_unique_friend_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_back',
            field=models.BooleanField(default=False, help_text='Whether lent money was returned'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for money given to friend', max_length=200),
        ),
    ]
